# Generated by Django 4.1.1 on 2022-09-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_message_room'),
        ('events', '0004_venue_venue_image'),
    ]

    operations = [
    ]
