# Generated by Django 3.2.12 on 2022-09-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_message_room'),
        ('events', '0004_venue_venue_image'),
    ]

    operations = [
    ]
